version: '3.3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${EXTERNAL_PORT_DB}:${INTERNAL_PORT_DB}
    networks:
      - app-tier
    volumes:
      - db:/var/lib/postgresql/data

  update_reviews:
    build: .
    command:
      - python -m nltk.downloader all
      - python update.py
    volumes:
      - .:/code
    restart: always
    depends_on:
      - db
    networks:
      - app-tier
volumes:
  db:
    driver: local

networks:
  app-tier:
    driver: bridge